### ISSUE TITLE
Problem about data pre-processing 

### ISSUE THREAD

**Issue by 2017211801** [mikecheninoulu/Unsupervised_IEPGAN#6]
Thank you for this wonderful work!
I have one questions about data pre-processing. When I use 'generate_geodesic_distance.py' to convert the OBj file you provided to GIH, I encountered  the following error:
`  f = torch.solve(U, B)[0]
Traceback (most recent call last):

  File "GIH_calculating/generate_geodesic_distance.py", line 39, in <module>
    Dg_r, grad, div, W, S, C = distance_GIH(mesh_points, mesh_faces) 

  File "/mnt/16T/sxk/Unsupervised_IEPGAN-main/GIH_calculating/utils_distance.py", line 122, in distance_GIH
    D = _geodesics_in_heat(grad,div,W[0],A,t)

  File "/mnt/16T/sxk/Unsupervised_IEPGAN-main/GIH_calculating/utils_distance.py", line 109, in _geodesics_in_heat
    f = torch.solve(U, B)[0]

RuntimeError: solve_cuda: The diagonal element 1 is zero, the solve could not be completed because the input matrix is singular.`
Can you explain it? Thank you again for your contribution.
Thanks,
xiaokun

**Comment by 2017211801** [comment]
The reason for the problem is that my pytorch version is too new, fixing it by replacing `f = torch.solve(U, B)[0]` with `f =  torch.linalg.solve(B, U)` in File "/mnt/16T/sxk/Unsupervised_IEPGAN-main/GIH_calculating/utils_distance.py", line 109.
Thank you again for your contribution.
